"""fix primary key

Revision ID: 0f0130b676fb
Revises: b6b2afe17839
Create Date: 2025-11-19 13:50:42.650288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f0130b676fb'
down_revision: Union[str, None] = 'b6b2afe17839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'transaction_no',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'bills', ['transaction_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='unique')
    op.alter_column('bills', 'transaction_no',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
